### ISSUE TITLE
Needs msvcr in old Windows versions

### ISSUE THREAD

**Issue by stuta** [sonoro1234/luafilesystem#1]
In older Windows versions and in wine you need to load msvcr for _findfirst.
```lua
if OS == 'Windows' then
		local ok
		ok, lib = pcall(ffi.load, "msvcr120.dll")
		if not ok then
			lib = ffi.load("msvcr100.dll")
		end
```

It would be nice to have cdef's in separate file because many libs define the same C functions and luajit does not allow redefines.

**Comment by sonoro1234** [comment]
This are two issues:

1-msvcrt

according to http://luajit.org/ext_ffi_api.html you shouldn't need to load msvcrt as the symbols are already loaded.
```
On Windows systems, this binds to symbols exported from the *.exe, the lua51.dll (i.e. the Lua/C API provided by LuaJIT itself), the C runtime library LuaJIT was linked with (msvcrt*.dll), kernel32.dll, user32.dll and gdi32.dll.
```
As LuaJIT is linked against this dlls, loading doesnt seem necessary
(I dont need it in windows 7 but could try windows vista also)
Did you compiled LuaJIT with original Makefile or  src/msvcbuild.bat?

2-redefines
The defines in lfs_ffi.lua are all related to filesystem functions: 
Which other modules would also define them?
I dont understand how having cdefs in separate file could help.

**Comment by stuta** [comment]
1. I have run previous versions of https://github.com/spacewander/luafilesystem.git in numerous Windows systems (WinXP, Win7, wine) that  do not have ```_findfirst``` defined without loading msvcr. Reality is stronger evidence than documentation and fix is easy.

2. Just a starter list of defines needed elsewhere: ```wchar_t, strerror, mbrtowc, all *time*, wcslen, wcsncpy, WideCharToMultiByte, GetLastError, FormatMessageA```..., I hope you get the point. There are more common definitions than only filesystem related because filesystem functions use common datatypes.

When ffi cdef's are in separate file I can use main file without modifications and create only my own subset of defines that I do not have already defined.

Also unicode functions should be in their own file. I don't want to have same code in many places and unicode functions are needed in many applications.

Anyway, great code.

**Comment by sonoro1234** [comment]
Perhaps a new branch could be created because this lfs_ffi.lua already satisfies some people needs: self-contained and unicode.
Instead of a branch perhaps another lfs_ffi could be developed in a directory with several files and a init.lua as you suggest.

some caveats
1.
- May be pcall(function() return ffi.C._findfirst end) should be used to test if ffi.load is necessary. (perhaps also after any ffi.load)
- mingw links to msvcrt.dll (not msvcrtXXX.dll) and it is always present so that ffi.load"msvcrt" would fail for nobody but surely would be bad for programs compiled with MSVC that will be still missing msvcrtXXX.dll
2.
- Yes you are right in case the user wants to load other windows specific ffi libraries (not my case)
- My experiments showed that functions can be redefined without problems but static const int and struct definitions complain.
 Perhaps

<code>
static const int FORMAT_MESSAGE_FROM_SYSTEM = 0x00001000;
 static const int FORMAT_MESSAGE_IGNORE_INSERTS = 0x00000200;
</code>

should be

<code>
static const int FORMAT_MESSAGE_FROM_SYSTEM_lfs = 0x00001000;
 static const int FORMAT_MESSAGE_IGNORE_INSERTS_lfs = 0x00000200;
</code>

Just made commit https://github.com/sonoro1234/luafilesystem/commit/9bcf29ae025980795480182a2077bcb9069775f0
avoiding static const int at all
- ffi.cdefs are scrambled in the code so that everything would need a big rework

As you seem to have clear ideas about what is needed I would suggest doing a PR that creates another branch or that sets an alternative lfs_ffi folder (with init.lua and so on) in this same branch

(The great code is from spacewander)

**Comment by stuta** [comment]
This works in wine too. There is no need to load plain msvcr.dll in any system.

```lua
		-- test if ffi.C is missing _findfirst
		local ok = pcall(function() return ffi.C._findfirst end)
		if ok == false then
			ok, lib = pcall(ffi.load, "msvcr120.dll")
			if ok == false then
				lib = ffi.load("msvcr100.dll")
			end
		end
```

Good tip about functions can be redefined. But I think it can lead to horribly hard to find bugs (sometimes you need to define different parameters for example x32/x64/wine) when something works before using some other file and does not work any more after redefine. Usually those crashes may show after hours or days of running the program.

My ideas came from creating 200k lines of server program that works in all platforms. Sorry, I don't have time to dig in to this until I have a real problem with unicode, I will use previous versions.

**Comment by sonoro1234** [comment]
The more I read and think about it, the more convinced I am that for a self-contained ffi that uses common definitions but that dont need to expose them (as this project) struct names and static const ints should be prefixed with some string (lfs in this case)

In the case of static const ints it would suffice to declare them as plain lua numbers as in https://github.com/sonoro1234/luafilesystem/commit/9bcf29ae025980795480182a2077bcb9069775f0

**Comment by stuta** [comment]
I tried the latest version in osx, can't start the program: ```attempt to redefine 'timespec'```. How are you going to handle these?

**Comment by sonoro1234** [comment]
Just pushed a commit renaming timespec to lfs_timespec and stat to lfs_stat but cant try in osx.
Solved the issue?

**Comment by stuta** [comment]
Now osx works, but windows has big amount of typedef structs that you have to rename too. And I have't tested linux. Every library redefining everything again is not a way I will go. Defines in different file is ok, spending non-productive time for things like this is not.
